# Generated by Django 5.1.1 on 2024-10-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_location_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Types',
                'ordering': ('name',),
            },
        ),
    ]
