# Generated by Django 5.1.1 on 2024-10-03 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listing_media')),
                ('large', models.ImageField(blank=True, null=True, upload_to='listing_media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='listing.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='listing.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='listing.type')),
            ],
        ),
    ]
