# Generated by Django 5.1.1 on 2024-10-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('title',), 'verbose_name_plural': 'Listings'},
        ),
    ]
